### ISSUE TITLE
Update nginx app with variable for cert manager cluster issuer

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slate-catalog-stable#116]
Update the `nginx` application allowing the specification of the cluster issuer, specifically the following Ingress annotations using `staging` as an example.
```yaml
annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-staging
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/ingress.class: slate
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Content-Security-Policy: frame-ancestors 'self' *.slateci.io *.slateci.net" "X-Frame-Options: allow-from *.slateci.io";
```
and the TLS information. For example:
```yaml
 tls:
  - hosts:
    - ingress-tls-test.uutah-prod.slateci.net
    secretName: ingress-tls-test
```
