### ISSUE TITLE
Enforce ImageTag value across all apps

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slate-catalog-stable#132]
In each `values.yaml`:
```yaml
# Supported values are e.g. 'latest', '1.0.0', etc.. Consult the
# hub.opensciencegrid.org/slate/v4a docker image for other tags.
ImageTag: '1.0.0'
```
In the `depoyment.yaml`, something like:
```yaml
spec:
  containers:
    - name: {{ .Chart.Name }}
      image: "hub.opensciencegrid.org/slate/v4a:{{ .Values.ImageTag }}"
```
