### ISSUE TITLE
Move XCache images to OSG Harbor where sensible

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slate-catalog-stable#135]
Move away from our custom `slateci/xcache` container image for the XCache SLATE application in favor of `opensciencegrid/atlas-xcache:fresh`.

**Comment by adamhgriffith-uofu** [comment]
Looks like this is going beyond a simple find/replace. For example, in `./charts/xcache/templates/deployment.yaml`:
```yaml
- name: {{ .Chart.Name }}
  image: "opensciencegrid/atlas-xcache:fresh"
  imagePullPolicy: Always
  env:
  - name: XC_SPACE_HIGH_WM
    value: {{ .Values.XCacheConfig.HighWaterMark | quote }}
  - name: XC_SPACE_LOW_WM
    value: {{ .Values.XCacheConfig.LowWaterMark | quote }}
  - name: XC_PORT
    value: {{ .Values.Service.Port | quote }}
  - name: XC_RAMSIZE
    value: {{ .Values.XCacheConfig.RamSize | quote }}
  - name: XC_BLOCKSIZE
    value: {{ .Values.XCacheConfig.BlockSize | quote }}
  - name: XC_PREFETCH
    value: {{ .Values.XCacheConfig.Prefetch | quote }}
  - name: XC_WQ_BLOCKS_PER_LOOP
    value: {{ .Values.XCacheConfig.WQBlocksPerLoop | quote}}
  - name: XC_WQ_THREADS
    value: {{ .Values.XCacheConfig.WQThreads | quote }}
  - name: XC_RESOURCENAME
    value: {{ .Values.SiteConfig.Name | quote }}
  - name: XC_MONITOR
    value: {{ .Values.Monitoring.GStreamCollector | quote }}
```
However the [atlas-xcache image config docs](https://hub.docker.com/r/opensciencegrid/atlas-xcache) mention a different set of environmental variables.
