### ISSUE TITLE
Update notify-api.yml github workflow to use separate API tokens

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slate-catalog-stable#58]
The arguments for `slateci/github-actions/.github/workflows/slate-updateapps.yml` is changing in `.github/workflows/notify-api.yml`. Update this file to match those changes, namely the new secrets args:
```yaml
    secrets:
      slate_api_token_dev:
        description: The SLATE API token used to communicate with the development SLATE API endpoint.
        required: true
      slate_api_token_staging:
        description: The SLATE API token used to communicate with the staging SLATE API endpoint.
        required: true
      slate_api_token_prod:
        description: The SLATE API token used to communicate with the production SLATE API endpoint.
        required: true
```
